[tool.poetry]
name = "cape-wf-bactopia-kraken2"
version = "0.0.0"
description = "CAPE workflow for Bactopia v3.2.0 and Kraken2 taxonomic classification"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
# Dependencies for CI type checking only - not distributed
boto3 = "*"
apache-airflow = {version = "^3.1.0", extras = ["amazon"]}
# TODO: Add capepy when needed for imports

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 80

[tool.isort]
profile = "black"
line_length = 80

[tool.ruff]
line-length = 80
